import { Action, IResourceItem, Refine } from "@refinedev/core";
import { DevtoolsProvider } from "@refinedev/devtools";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";

import routerBindings, {
  DocumentTitleHandler,
  UnsavedChangesNotifier,
} from "@refinedev/react-router";
import { BrowserRouter } from "react-router";
import { authProvider, notificationProvider } from "./providers";
import { dataProviders, endpointResources } from "./pages/resources";
import PageRoutes from "./pages/routes";

function App() {
  const handleDocumentTitle = (_: {
    resource?: IResourceItem;
    action?: Action;
    params?: Record<string, string | undefined>;
    pathname?: string;
    autoGeneratedTitle: string;
  }) => {
    _;
    return "GetHealthy | Admin";
  };

  return (
    <BrowserRouter>
      <RefineKbarProvider>
        <DevtoolsProvider>
          <Refine
            dataProvider={dataProviders}
            routerProvider={routerBindings}
            authProvider={authProvider}
            notificationProvider={notificationProvider}
            resources={endpointResources}
            options={{
              syncWithLocation: true,
              warnWhenUnsavedChanges: true,
            }}
          >
            <PageRoutes />
            <RefineKbar />
            <UnsavedChangesNotifier />
            <DocumentTitleHandler handler={handleDocumentTitle} />
          </Refine>
          {/* <DevtoolsPanel /> */}
        </DevtoolsProvider>
      </RefineKbarProvider>
    </BrowserRouter>
  );
}

export default App;
